서기: 박선영

reshape 함수를 (-1, 1)의 형태로 사용하게 되면 원 배열이 열의 형태로 나타나게 되고, (1, -1)의 형태로 사용하게 되면 원 배열이 행의 형태로 나타남. 또, 행은 axis = 0, 열은 axis = 1로 표기함. 헷갈리면 열은 1모양이라고 생각하기,,

In [2]:
import numpy as np

In [14]:
array1 = np.zeros((4,2))

array2 = array1.reshape(-1,1)

print(array2.shape)

print(array1)
print(array2)

(8, 1)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [18]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)

print(array1d)
print(array2d)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
array2d[:2, 0]

array([1, 4])

In [20]:
array2d[0, :2]

array([1, 2])